force-app/main/default/objects/MC_SMS__e/MC_SMS__e.object-meta.xml
<CustomObject>
    <label>MC SMS</label>
    <pluralLabel>MC SMS</pluralLabel>
</CustomObject>

force-app/main/default/objects/MC_SMS__e/fields/countryCode__c.field-meta.xml
<CustomField>
    <fullName>countryCode__c</fullName>
    <label>countryCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_SMS__e/fields/messageContent__c.field-meta.xml
<CustomField>
    <fullName>messageContent__c</fullName>
    <label>messageContent</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MC_SMS__e/fields/mobileNumber__c.field-meta.xml
<CustomField>
    <fullName>mobileNumber__c</fullName>
    <label>mobileNumber</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_SMS__e/fields/reformatNumber__c.field-meta.xml
<CustomField>
    <fullName>reformatNumber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>reformatNumber</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MC_SendSmsPEAction.cls
public class MC_SendSmsPEAction {

    @InvocableMethod(label='Send SMS Platform Event')
    public static void execute(List<RequestInput> inputList) {
        
        System.debug('* Creating MC_SMS Platform Event');
        
        RequestInput input = inputList[0];
        
        MC_SMS__e ev = new MC_SMS__e();
        ev.mobileNumber__c = input.mobileNumber;
        ev.messageContent__c = input.messageContent.left(160);
        ev.reformatNumber__c = (input.reformatNumber == 1) ? true : false;
        ev.countryCode__c = input.countryCode;
        
        System.debug('** Event Record: ' + ev);
        
        Database.SaveResult result = EventBus.publish(ev);
        System.debug('** Save Result: ' + result);
        
    }
    
    public class RequestInput {
        
        @InvocableVariable public String mobileNumber;
        @InvocableVariable public String messageContent;
        @InvocableVariable public Integer reformatNumber;
        @InvocableVariable public String countryCode;
        
    }
}