force-app/main/default/objects/MC_Case__e/MC_Case__e.object-meta.xml
<CustomObject>
    <label>MC Case</label>
    <pluralLabel>MC Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/MC_Case__e/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/origin__c.field-meta.xml
<CustomField>
    <fullName>origin__c</fullName>
    <label>origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/otherFields__c.field-meta.xml
<CustomField>
    <fullName>otherFields__c</fullName>
    <label>otherFields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/priority__c.field-meta.xml
<CustomField>
    <fullName>priority__c</fullName>
    <label>priority</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/recipientId__c.field-meta.xml
<CustomField>
    <fullName>recipientId__c</fullName>
    <label>recipientId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/recordTypeName__c.field-meta.xml
<CustomField>
    <fullName>recordTypeName__c</fullName>
    <label>recordTypeName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/subject__c.field-meta.xml
<CustomField>
    <fullName>subject__c</fullName>
    <label>subject</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MC_Case__e/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MC_CreateCasePEAction.cls
public class MC_CreateCasePEAction {

    @InvocableMethod(label='Send Create Case Platform Event')
    public static void execute(List<RequestInput> inputList) {
     
        System.debug('* Creating MC_Case Platform Event');
        
        RequestInput input = inputList[0];
        
        MC_Case__e ev = new MC_Case__e();
        ev.subject__c = input.subject;
        ev.description__c = input.description;
        ev.priority__c = input.priority;
        ev.origin__c = input.origin;
        ev.type__c = input.type;
        ev.recordTypeName__c = input.recordTypeName;
        ev.recipientId__c = input.recipientId;
        ev.otherFields__c = input.otherFields;
        
        System.debug('** Event Record: ' + ev);
        
        Database.SaveResult result = EventBus.publish(ev);
        System.debug('** Save Result: ' + result);
        
    }

    public class RequestInput {
        @InvocableVariable(required=true label='Case Subject') public String subject;
        @InvocableVariable(label='Case Description') public String description;
        @InvocableVariable(label='Case Priority') public String priority;
        @InvocableVariable(label='Case Origin') public String origin;
        @InvocableVariable(label='Case Type') public String type;
        @InvocableVariable(label='Record Type DeveloperName') public String recordTypeName;
        @InvocableVariable(label='Recipient Id') public String recipientId;
        @InvocableVariable(label='Other Fields') public String otherFields;
    }
    
}